# Generated by Django 3.0.3 on 2020-02-14 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEIVDCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('check_required_ce_ivd', models.BooleanField()),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IGCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('check_profiling_or_automated_decisions', models.BooleanField()),
                ('check_special_category_data', models.BooleanField()),
                ('check_monitor_publically_accessible_place', models.BooleanField()),
                ('check_innovative_technology', models.BooleanField()),
                ('check_decision_on_service_access', models.BooleanField()),
                ('check_large_scale_profiling', models.BooleanField()),
                ('check_process_biometric_or_genetic_data', models.BooleanField()),
                ('check_combine_compare_or_match_data', models.BooleanField()),
                ('check_personal_data_without_privacy_notice', models.BooleanField()),
                ('check_track_behaviour_or_location', models.BooleanField()),
                ('check_process_childrens_data', models.BooleanField()),
                ('check_risk_of_physical_harm_upon_breach', models.BooleanField()),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('Routine', 'Routine'), ('Service Provision', 'Service Provision'), ('Research', 'Research')], max_length=254)),
                ('summary', models.CharField(max_length=500)),
                ('impact', models.CharField(max_length=500)),
                ('strategy', models.CharField(max_length=500)),
                ('is_clinical_software', models.BooleanField()),
                ('ce_ivd_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.CEIVDCheck')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.Hub')),
                ('ig_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.IGCheck')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('1', 'Suggestion'), ('2', 'Validation'), ('3', 'Verification'), ('4', 'Final Decision'), ('5', 'Implemented')], max_length=254)),
                ('requires_dpia', models.BooleanField(null=True)),
                ('requires_ce_ivd', models.BooleanField(null=True)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.ChangeSuggestion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
