# Generated by Django 3.0.3 on 2020-02-14 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0002_ceivdcheck_change_changesuggestion_igcheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changesuggestion',
            old_name='type',
            new_name='change_type',
        ),
        migrations.RemoveField(
            model_name='change',
            name='suggestion',
        ),
        migrations.AddField(
            model_name='change',
            name='index',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changesuggestion',
            name='change',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='db.Change'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChangeSuggestionReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('pending', models.BooleanField()),
                ('outcome', models.CharField(choices=[('A', 'Accepted'), ('I', 'Additional Information Required'), ('S', 'Shelved')], max_length=1)),
                ('change', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Change')),
                ('reviewers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suggestion_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='changesuggestion',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.ChangeSuggestionReview'),
        ),
    ]
