# Generated by Django 3.0.3 on 2020-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20200214_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igcheck',
            name='check_combine_compare_or_match_data',
        ),
        migrations.RemoveField(
            model_name='igcheck',
            name='check_decision_on_service_access',
        ),
        migrations.RemoveField(
            model_name='igcheck',
            name='check_innovative_technology',
        ),
        migrations.RemoveField(
            model_name='igcheck',
            name='check_large_scale_profiling',
        ),
        migrations.RemoveField(
            model_name='igcheck',
            name='check_monitor_publically_accessible_place',
        ),
        migrations.RemoveField(
            model_name='igcheck',
            name='check_personal_data_without_privacy_notice',
        ),
        migrations.RemoveField(
            model_name='igcheck',
            name='check_process_biometric_or_genetic_data',
        ),
        migrations.RemoveField(
            model_name='igcheck',
            name='check_process_childrens_data',
        ),
        migrations.RemoveField(
            model_name='igcheck',
            name='check_profiling_or_automated_decisions',
        ),
        migrations.RemoveField(
            model_name='igcheck',
            name='check_risk_of_physical_harm_upon_breach',
        ),
        migrations.RemoveField(
            model_name='igcheck',
            name='check_special_category_data',
        ),
        migrations.RemoveField(
            model_name='igcheck',
            name='check_track_behaviour_or_location',
        ),
        migrations.AddField(
            model_name='igcheck',
            name='check_collect_new_info',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='igcheck',
            name='check_compel_provision_of_info',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='igcheck',
            name='check_decisions_with_significant_impact',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='igcheck',
            name='check_disclosed_to_new_3rd_party',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='igcheck',
            name='check_health_or_wellbeing_info',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='igcheck',
            name='check_intrusive_contact',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='igcheck',
            name='check_new_privacy_intrusive_technology',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='igcheck',
            name='check_new_purpose',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
