# Generated by Django 3.0.3 on 2020-02-07 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.Hub'),
        ),
    ]
