# Generated by Django 3.0.3 on 2020-02-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
        ('accounts', '0002_user_hub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hub',
        ),
        migrations.AddField(
            model_name='user',
            name='hubs',
            field=models.ManyToManyField(null=True, related_name='staff', to='db.Hub'),
        ),
    ]
