# Generated by Django 3.0.3 on 2020-02-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
        ('accounts', '0003_auto_20200207_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hubs',
            field=models.ManyToManyField(related_name='staff', to='db.Hub'),
        ),
    ]
