# Generated by Django 3.0.3 on 2020-02-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200207_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=None, max_length=80),
            preserve_default=False,
        ),
    ]
