# Generated by Django 3.0.3 on 2020-02-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='band',
            field=models.CharField(choices=[('1', 'Band 1'), ('2', 'Band 2'), ('3', 'Band 3'), ('4', 'Band 4'), ('5', 'Band 5'), ('6', 'Band 6'), ('7', 'Band 7'), ('8a', 'Band 8A'), ('8b', 'Band 8B'), ('8c', 'Band 8C'), ('8d', 'Band 8D'), ('9', 'Band 9'), ('N', 'Not Set')], default='N', max_length=2),
        ),
    ]
